### ISSUE TITLE
custom resource declaration compatibility with Chef infra client v 16.2.44+

### ISSUE THREAD

**Issue by nicknameyu** [dev-sec/chef-windows-hardening#50]
custom resource declaration for 'password_policy' need to be updated to sync with Chef infra client v16.2.44+
**Pre-16 code:**
resource_name :foo

**Chef Infra Client 16+ code**
provides :foo

**Chef Infra Client < 16 backwards compatible code**
resource_name :foo
provides :foo

**Comment by tas50** [comment]
This has been fixed on master

**Comment by IrynaAbikh** [comment]
@tas50, Looks like version '0.9.1' from supermarket.chef.io does not contain this fix since the version in #49 wasn`t bumped.
Could you please fix it?

**Comment by tas50** [comment]
Someone with permissions on this project will need to cut a new release and push it to supermarket.

**Comment by idiudiuki** [comment]
Hi @tas50, we experience the same problem. Do we need to open a new issue for this as this one is closed? How long do you think it will take to apply this update?

**Comment by tas50** [comment]
You could open an issue requesting a release be made. That may help the process. I'm not sure who is still actively maintaining this project.
