### ISSUE TITLE
Rename recipes to be component-oriented

### ISSUE THREAD

**Issue by chris-rock** [dev-sec/chef-windows-hardening#9]
The current recipes are following the numbers by https://github.com/dev-sec/windows-baseline/tree/master/controls

Instead I propose we are using a component-oriented model like in https://github.com/dev-sec/chef-os-hardening/tree/master/recipes

**Comment by MattTunny** [comment]
yeah that would be awesome, I was having trouble reading how to I needed to add my changes, wasn't sure if the numbers where referencing some documentation.
